<?php
declare(strict_types=1);

$pageTitle = 'Grades Management';
$pageKey = 'examination_management';
require dirname(__DIR__) . '/includes/layout-start.php';

if (session_status() !== PHP_SESSION_ACTIVE) {
    session_start();
}
if (empty($_SESSION['grades_csrf_token']) || !is_string($_SESSION['grades_csrf_token'])) {
    $_SESSION['grades_csrf_token'] = bin2hex(random_bytes(32));
}
$gradesCsrf = $_SESSION['grades_csrf_token'];
?>
<style>
.grades-page{display:grid;gap:16px}
.grades-page .page-title{font-size:28px;line-height:1.1}.grades-page .page-subtitle{margin-top:4px}
.grades-message{display:none}.grades-message.show{display:block}
.grades-stats{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:14px}
.grades-stat{border-radius:14px;min-height:110px;padding:18px 20px;display:flex;align-items:center;gap:14px;color:#fff;position:relative;overflow:hidden;box-shadow:0 12px 28px rgba(15,23,42,.08)}
.grades-stat::after{content:"";position:absolute;width:110px;height:110px;border-radius:50%;right:-38px;top:-40px;background:rgba(255,255,255,.08)}
.grades-stat.purple{background:linear-gradient(135deg,#7448e8,#4b36cf)}.grades-stat.green{background:linear-gradient(135deg,#45c783,#1ea568)}.grades-stat.orange{background:linear-gradient(135deg,#ffb327,#ff8a17)}.grades-stat.blue{background:linear-gradient(135deg,#4696ef,#2469d5)}
.grades-stat-icon{width:50px;height:50px;border-radius:50%;background:rgba(255,255,255,.16);display:grid;place-items:center;flex:0 0 auto}.grades-stat-icon svg{width:25px;height:25px}
.grades-stat strong{display:block;font-size:25px;line-height:1}.grades-stat small{display:block;font-size:11px;font-weight:700;opacity:.95;margin-bottom:6px}.grades-stat .trend{font-size:9px;font-weight:700;opacity:.94;margin-top:8px}
.grades-tabs{display:flex;gap:8px;overflow:auto;padding:10px}.grades-tab{border:1px solid var(--border-soft,#e7ebf3);background:var(--card-bg,#fff);color:var(--text-main,#101b46);border-radius:9px;padding:9px 12px;font-size:11px;font-weight:800;white-space:nowrap}.grades-tab.active{color:#fff;border-color:transparent;background:linear-gradient(135deg,#6747e8,#2f62d7)}
.grades-panel{display:none}.grades-panel.active{display:block}.grades-card{border-radius:14px;overflow:hidden}.grades-card-head{padding:14px 16px;border-bottom:1px solid var(--border-soft,#e7ebf3);display:flex;justify-content:space-between;align-items:center;gap:10px}.grades-card-actions{display:flex;gap:8px;flex-wrap:wrap}
.grades-filter{padding:14px 16px;display:grid;grid-template-columns:minmax(220px,1.3fr) repeat(5,minmax(135px,.7fr)) auto;gap:10px;border-bottom:1px solid var(--border-soft,#e7ebf3)}
.grades-table-wrap{overflow:auto}.grades-table{min-width:1250px}.grades-table.compact{min-width:900px}.grades-table th{font-size:10px}.grades-table td{font-size:11px;vertical-align:middle}.grades-empty{padding:40px 18px!important;text-align:center!important;color:var(--text-muted,#64748b)}
.grades-badge{display:inline-flex;align-items:center;padding:5px 9px;border-radius:999px;font-size:9px;font-weight:800;text-transform:capitalize}.grades-badge.active,.grades-badge.pass,.grades-badge.published,.grades-badge.success{color:#16834f;background:#e8f8ef}.grades-badge.inactive,.grades-badge.fail,.grades-badge.cancelled{color:#dc2626;background:#fff0f1}.grades-badge.draft,.grades-badge.pending{color:#9a6700;background:#fff7d6}
.grades-actions{display:flex;gap:5px;flex-wrap:wrap}.grades-action{width:30px;height:30px;display:grid;place-items:center;border:1px solid #d7def1;border-radius:7px;background:var(--card-bg,#fff);color:#4f46e5}.grades-action.danger{color:#dc2626}.grades-action.success{color:#16834f}.grades-action svg{width:13px;height:13px}
.grades-pagination{padding:14px 16px;border-top:1px solid var(--border-soft,#e7ebf3);display:flex;justify-content:space-between;align-items:center;gap:10px}.grades-page-buttons{display:flex;gap:6px;flex-wrap:wrap}.grades-page-button{min-width:34px;height:34px;border:1px solid var(--border-soft,#e7ebf3);background:#fff;border-radius:8px;font-size:11px;font-weight:800}.grades-page-button.active{color:#fff;border-color:transparent;background:linear-gradient(135deg,#6547e8,#315ed8)}
.grades-form-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.grades-form-grid .full{grid-column:1/-1}.grades-summary{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px}.grades-summary>div{border:1px solid var(--border-soft,#e7ebf3);border-radius:10px;padding:12px}.grades-summary small{display:block;font-size:9px;color:var(--text-muted,#64748b);font-weight:700}.grades-summary strong{display:block;margin-top:4px;font-size:14px}
#systemModal .modal-dialog,#ruleModal .modal-dialog,#gradeModal .modal-dialog,#viewModal .modal-dialog{max-height:calc(100dvh - 32px);margin:16px auto}#systemModal .modal-content,#ruleModal .modal-content,#gradeModal .modal-content,#viewModal .modal-content{max-height:calc(100dvh - 32px);overflow:hidden}#systemModal form,#ruleModal form,#gradeModal form{display:flex;flex-direction:column;max-height:calc(100dvh - 32px)}#systemModal .modal-body,#ruleModal .modal-body,#gradeModal .modal-body,#viewModal .modal-body{overflow-y:auto;min-height:0}
@media(max-width:1200px){.grades-filter{grid-template-columns:repeat(3,1fr)}}@media(max-width:900px){.grades-stats,.grades-summary{grid-template-columns:repeat(2,1fr)}}@media(max-width:575px){.grades-stats,.grades-filter,.grades-form-grid,.grades-summary{grid-template-columns:1fr}.grades-form-grid .full{grid-column:auto}.grades-card-head,.grades-pagination{align-items:flex-start;flex-direction:column}}
</style>

<div class="grades-page" data-page="grades">
<div class="page-heading">
 <div><h1 class="page-title">Grades Management</h1><p class="page-subtitle">Configure grading systems, calculate student grades and publish academic results.</p></div>
 <div class="page-actions">
  <button id="addGradeBtn" class="btn-ui btn-primary-ui" type="button"><i data-lucide="plus"></i> Add Student Grade</button>
  <button id="addSystemBtn" class="btn-ui" type="button"><i data-lucide="badge-plus"></i> Grade System</button>
  <button id="exportBtn" class="btn-ui" type="button"><i data-lucide="download"></i> Export</button>
  <button id="printBtn" class="btn-ui" type="button"><i data-lucide="printer"></i> Print</button>
  <button id="refreshBtn" class="btn-ui" type="button"><i data-lucide="refresh-cw"></i> Refresh</button>
 </div>
</div>

<div id="gradesMessage" class="alert grades-message"></div>

<section class="grades-stats">
 <article class="grades-stat purple"><span class="grades-stat-icon"><i data-lucide="graduation-cap"></i></span><div><small>Grade Systems</small><strong id="statSystems">0</strong><div class="trend">Configured grading systems</div></div></article>
 <article class="grades-stat green"><span class="grades-stat-icon"><i data-lucide="badge-check"></i></span><div><small>Active Grade Rules</small><strong id="statRules">0</strong><div class="trend">Rules available for calculation</div></div></article>
 <article class="grades-stat orange"><span class="grades-stat-icon"><i data-lucide="users"></i></span><div><small>Students Evaluated</small><strong id="statStudents">0</strong><div class="trend">Distinct graded students</div></div></article>
 <article class="grades-stat blue"><span class="grades-stat-icon"><i data-lucide="send"></i></span><div><small>Published Results</small><strong id="statPublished">0</strong><div class="trend">Published grade records</div></div></article>
</section>

<section class="ui-card grades-tabs">
 <button class="grades-tab active" data-tab="dashboard" type="button">Grade Dashboard</button>
 <button class="grades-tab" data-tab="systems" type="button">Grade Systems</button>
 <button class="grades-tab" data-tab="rules" type="button">Grade Rules</button>
 <button class="grades-tab" data-tab="student" type="button">Student Grades</button>
 <button class="grades-tab" data-tab="reports" type="button">Reports</button>
 <button class="grades-tab" data-tab="history" type="button">Logs & History</button>
</section>

<section class="grades-panel active" data-panel="dashboard">
 <section class="ui-card grades-card">
  <div class="grades-card-head"><strong>Recent Student Grades</strong><small id="recordInfo" class="text-muted">Loading...</small></div>
  <div class="grades-filter">
   <input id="search" class="form-control" placeholder="Student, admission no., exam or subject...">
   <select id="yearFilter" class="form-select"><option value="all">All Academic Years</option></select>
   <select id="classFilter" class="form-select"><option value="all">All Classes</option></select>
   <select id="sectionFilter" class="form-select"><option value="all">All Sections</option></select>
   <select id="subjectFilter" class="form-select"><option value="all">All Subjects</option></select>
   <select id="publishFilter" class="form-select"><option value="all">All Result Statuses</option><option value="draft">Draft</option><option value="published">Published</option></select>
   <button id="resetBtn" class="btn-ui" type="button"><i data-lucide="rotate-ccw"></i> Reset</button>
  </div>
  <div class="grades-table-wrap"><table class="data-table grades-table"><thead><tr><th>#</th><th>Student</th><th>Admission No.</th><th>Academic Year</th><th>Class / Section</th><th>Exam</th><th>Subject</th><th>Marks</th><th>%</th><th>Grade</th><th>Result</th><th>Publish</th><th>Actions</th></tr></thead><tbody id="gradeBody"><tr><td colspan="13" class="grades-empty">Loading...</td></tr></tbody></table></div>
  <div class="grades-pagination"><small id="pageInfo" class="text-muted"></small><div id="pagination" class="grades-page-buttons"></div></div>
 </section>
</section>

<section class="grades-panel" data-panel="systems">
 <section class="ui-card grades-card">
  <div class="grades-card-head"><strong>Grade Systems</strong><button id="panelAddSystemBtn" class="btn-ui btn-primary-ui" type="button"><i data-lucide="plus"></i> Add System</button></div>
  <div class="grades-table-wrap"><table class="data-table grades-table compact"><thead><tr><th>#</th><th>System Name</th><th>Academic Year</th><th>Calculation</th><th>Default</th><th>Rules</th><th>Status</th><th>Actions</th></tr></thead><tbody id="systemBody"></tbody></table></div>
 </section>
</section>

<section class="grades-panel" data-panel="rules">
 <section class="ui-card grades-card">
  <div class="grades-card-head"><strong>Grade Rules</strong><button id="addRuleBtn" class="btn-ui btn-primary-ui" type="button"><i data-lucide="plus"></i> Add Rule</button></div>
  <div class="grades-table-wrap"><table class="data-table grades-table compact"><thead><tr><th>#</th><th>System</th><th>Grade</th><th>Percentage Range</th><th>Grade Point</th><th>Result</th><th>Remarks</th><th>Status</th><th>Actions</th></tr></thead><tbody id="ruleBody"></tbody></table></div>
 </section>
</section>

<section class="grades-panel" data-panel="student">
 <section class="ui-card grades-card">
  <div class="grades-card-head"><strong>Student Grade Entry</strong><button id="panelAddGradeBtn" class="btn-ui btn-primary-ui" type="button"><i data-lucide="plus"></i> Add Student Grade</button></div>
  <div class="p-3 text-muted" style="font-size:12px">Use the filters on the Grade Dashboard to locate results. Marks, percentage, grade, grade point and pass/fail status are calculated automatically from the selected grade system.</div>
 </section>
</section>

<section class="grades-panel" data-panel="reports">
 <section class="ui-card grades-card">
  <div class="grades-card-head"><strong>Grade Distribution Report</strong></div>
  <div class="grades-table-wrap"><table class="data-table grades-table compact"><thead><tr><th>Grade</th><th>Students</th><th>Passed</th><th>Failed</th><th>Average %</th><th>Published</th></tr></thead><tbody id="summaryBody"></tbody></table></div>
 </section>
</section>

<section class="grades-panel" data-panel="history">
 <section class="ui-card grades-card">
  <div class="grades-card-head"><strong>Grades Audit History</strong></div>
  <div class="grades-table-wrap"><table class="data-table grades-table compact"><thead><tr><th>Date</th><th>Action</th><th>Record</th><th>User</th><th>Details</th></tr></thead><tbody id="historyBody"></tbody></table></div>
 </section>
</section>
</div>

<div class="modal fade" id="systemModal" tabindex="-1"><div class="modal-dialog modal-lg modal-dialog-centered"><div class="modal-content"><form id="systemForm">
<div class="modal-header"><h5 id="systemModalTitle" class="modal-title">Add Grade System</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div>
<div class="modal-body grades-form-grid"><input id="systemId" type="hidden"><div><label class="form-label">System Name *</label><input id="systemName" class="form-control" maxlength="120" required></div><div><label class="form-label">Academic Year</label><select id="systemYear" class="form-select"></select></div><div><label class="form-label">Calculation Type *</label><select id="calculationType" class="form-select"><option value="percentage">Percentage</option><option value="marks">Marks</option><option value="gpa">GPA</option></select></div><div><label class="form-label">Status *</label><select id="systemStatus" class="form-select"><option value="active">Active</option><option value="inactive">Inactive</option></select></div><div><label class="form-label">Default System</label><select id="isDefault" class="form-select"><option value="0">No</option><option value="1">Yes</option></select></div><div class="full"><label class="form-label">Description</label><textarea id="systemDescription" class="form-control" rows="3" maxlength="500"></textarea></div></div>
<div class="modal-footer"><button type="button" class="btn-ui" data-bs-dismiss="modal">Cancel</button><button type="submit" class="btn-ui btn-primary-ui">Save System</button></div></form></div></div></div>

<div class="modal fade" id="ruleModal" tabindex="-1"><div class="modal-dialog modal-lg modal-dialog-centered"><div class="modal-content"><form id="ruleForm">
<div class="modal-header"><h5 id="ruleModalTitle" class="modal-title">Add Grade Rule</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div>
<div class="modal-body grades-form-grid"><input id="ruleId" type="hidden"><div><label class="form-label">Grade System *</label><select id="ruleSystem" class="form-select" required></select></div><div><label class="form-label">Grade Name *</label><input id="gradeName" class="form-control" maxlength="20" placeholder="A+" required></div><div><label class="form-label">Minimum Percentage *</label><input id="minPercentage" class="form-control" type="number" min="0" max="100" step="0.01" required></div><div><label class="form-label">Maximum Percentage *</label><input id="maxPercentage" class="form-control" type="number" min="0" max="100" step="0.01" required></div><div><label class="form-label">Grade Point *</label><input id="gradePoint" class="form-control" type="number" min="0" max="10" step="0.01" required></div><div><label class="form-label">Result *</label><select id="resultStatus" class="form-select"><option value="pass">Pass</option><option value="fail">Fail</option></select></div><div><label class="form-label">Status *</label><select id="ruleStatus" class="form-select"><option value="active">Active</option><option value="inactive">Inactive</option></select></div><div><label class="form-label">Display Order</label><input id="displayOrder" class="form-control" type="number" min="0" max="9999" value="0"></div><div class="full"><label class="form-label">Remarks</label><input id="ruleRemarks" class="form-control" maxlength="255"></div></div>
<div class="modal-footer"><button type="button" class="btn-ui" data-bs-dismiss="modal">Cancel</button><button type="submit" class="btn-ui btn-primary-ui">Save Rule</button></div></form></div></div></div>

<div class="modal fade" id="gradeModal" tabindex="-1"><div class="modal-dialog modal-xl modal-dialog-centered"><div class="modal-content"><form id="gradeForm">
<div class="modal-header"><h5 id="gradeModalTitle" class="modal-title">Add Student Grade</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div>
<div class="modal-body grades-form-grid"><input id="studentGradeId" type="hidden"><div><label class="form-label">Academic Year *</label><select id="gradeYear" class="form-select" required></select></div><div><label class="form-label">Grade System *</label><select id="gradeSystem" class="form-select" required></select></div><div><label class="form-label">Class *</label><select id="gradeClass" class="form-select" required></select></div><div><label class="form-label">Section</label><select id="gradeSection" class="form-select"></select></div><div><label class="form-label">Student *</label><select id="gradeStudent" class="form-select" required></select></div><div><label class="form-label">Subject *</label><select id="gradeSubject" class="form-select" required></select></div><div><label class="form-label">Exam Name *</label><input id="examName" class="form-control" maxlength="120" placeholder="Annual Examination" required></div><div><label class="form-label">Exam Date</label><input id="examDate" class="form-control" type="date"></div><div><label class="form-label">Marks Obtained *</label><input id="marksObtained" class="form-control" type="number" min="0" step="0.01" required></div><div><label class="form-label">Maximum Marks *</label><input id="maximumMarks" class="form-control" type="number" min="0.01" step="0.01" value="100" required></div><div><label class="form-label">Publish Status *</label><select id="publishStatus" class="form-select"><option value="draft">Draft</option><option value="published">Published</option></select></div><div><label class="form-label">Remarks</label><input id="gradeRemarks" class="form-control" maxlength="255"></div><div class="full alert alert-light mb-0"><strong>Automatic calculation:</strong> Percentage, grade, grade point and pass/fail result are determined by the active rules in the selected grade system.</div></div>
<div class="modal-footer"><button type="button" class="btn-ui" data-bs-dismiss="modal">Cancel</button><button type="submit" class="btn-ui btn-primary-ui">Save Grade</button></div></form></div></div></div>

<div class="modal fade" id="viewModal" tabindex="-1"><div class="modal-dialog modal-xl modal-dialog-centered"><div class="modal-content"><div class="modal-header"><div><h5 class="modal-title">Student Grade Details</h5><small id="viewSubtitle" class="text-muted"></small></div><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div id="viewContent" class="grades-summary"></div><div class="mt-3"><strong>Remarks</strong></div><div id="viewRemarks" class="alert alert-light mt-2 mb-0"></div></div><div class="modal-footer"><button type="button" class="btn-ui" data-bs-dismiss="modal">Close</button></div></div></div></div>

<script>
(function(){
'use strict';
const apiUrl=new URL('../api/grades.php',window.location.href).href;
let csrfToken=<?=json_encode($gradesCsrf)?>;
let meta={years:[],classes:[],sections:[],subjects:[],students:[],systems:[]};
let gradeRows=[],systemRows=[],ruleRows=[],page=1,permissions={edit:false,delete:false,publish:false};
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const number=v=>new Intl.NumberFormat('en-IN',{maximumFractionDigits:2}).format(Number(v||0));
const badge=v=>`<span class="grades-badge ${esc(String(v||'').toLowerCase())}">${esc(v||'-')}</span>`;
async function request(action,data={},method='GET'){let response;if(method==='GET'){const url=new URL(apiUrl);url.searchParams.set('action',action);Object.entries(data).forEach(([k,v])=>{if(v!==''&&v!==null&&v!==undefined)url.searchParams.set(k,String(v))});response=await fetch(url,{headers:{Accept:'application/json'},credentials:'same-origin'});}else{response=await fetch(apiUrl,{method:'POST',headers:{'Content-Type':'application/json',Accept:'application/json'},credentials:'same-origin',body:JSON.stringify({action,csrf_token:csrfToken,...data})});}const text=await response.text();let result;try{result=JSON.parse(text)}catch{throw new Error(`Grades API returned HTTP ${response.status}. ${text.replace(/\s+/g,' ').trim().slice(0,220)||'Invalid server response.'}`)}if(!response.ok||!result.success)throw new Error(result.message||'Request failed.');if(result.data?.csrf_token)csrfToken=result.data.csrf_token;return result;}
function message(text,ok=false){const b=$('gradesMessage');b.className='alert grades-message show '+(ok?'alert-success':'alert-danger');b.textContent=text;window.scrollTo({top:0,behavior:'smooth'});}
function fill(id,items,key,label,first=''){const e=$(id);e.innerHTML=(first?`<option value="">${esc(first)}</option>`:'')+items.map(x=>`<option value="${esc(x[key])}">${esc(x[label])}</option>`).join('');}
function updateStats(s={}){$('statSystems').textContent=Number(s.total_systems||0).toLocaleString('en-IN');$('statRules').textContent=Number(s.active_rules||0).toLocaleString('en-IN');$('statStudents').textContent=Number(s.students_evaluated||0).toLocaleString('en-IN');$('statPublished').textContent=Number(s.published_results||0).toLocaleString('en-IN');}
function renderGrades(data){gradeRows=data;$('gradeBody').innerHTML=data.map(r=>`<tr><td>${r.row_number}</td><td><strong>${esc(r.student_name)}</strong></td><td>${esc(r.admission_no)}</td><td>${esc(r.academic_year_name)}</td><td>${esc(r.class_name)} / ${esc(r.section_name||'-')}</td><td>${esc(r.exam_name)}</td><td>${esc(r.subject_name)}</td><td>${number(r.marks_obtained)} / ${number(r.maximum_marks)}</td><td>${number(r.percentage)}%</td><td><strong>${esc(r.grade_name)}</strong> (${number(r.grade_point)})</td><td>${badge(r.result_status)}</td><td>${badge(r.publish_status)}</td><td><div class="grades-actions"><button class="grades-action js-view" data-id="${r.id}" title="View"><i data-lucide="eye"></i></button>${permissions.edit?`<button class="grades-action js-edit" data-id="${r.id}" title="Edit"><i data-lucide="pencil"></i></button>`:''}${permissions.publish&&r.publish_status!=='published'?`<button class="grades-action success js-publish" data-id="${r.id}" title="Publish"><i data-lucide="send"></i></button>`:''}${permissions.delete?`<button class="grades-action danger js-delete" data-id="${r.id}" title="Delete"><i data-lucide="trash-2"></i></button>`:''}</div></td></tr>`).join('')||'<tr><td colspan="13" class="grades-empty">No student grades found.</td></tr>';document.querySelectorAll('.js-view').forEach(b=>b.onclick=()=>viewGrade(Number(b.dataset.id)));document.querySelectorAll('.js-edit').forEach(b=>b.onclick=()=>openGrade(Number(b.dataset.id)));document.querySelectorAll('.js-publish').forEach(b=>b.onclick=()=>publishGrade(Number(b.dataset.id)));document.querySelectorAll('.js-delete').forEach(b=>b.onclick=()=>deleteGrade(Number(b.dataset.id)));window.lucide?.createIcons();}
function renderSystems(data){systemRows=data;$('systemBody').innerHTML=data.map((r,i)=>`<tr><td>${i+1}</td><td><strong>${esc(r.system_name)}</strong></td><td>${esc(r.year_name||'All Years')}</td><td>${esc(r.calculation_type)}</td><td>${Number(r.is_default)?badge('active'):badge('inactive')}</td><td>${Number(r.rule_count||0)}</td><td>${badge(r.status)}</td><td><div class="grades-actions">${permissions.edit?`<button class="grades-action system-edit" data-id="${r.id}"><i data-lucide="pencil"></i></button>`:''}${permissions.delete?`<button class="grades-action danger system-delete" data-id="${r.id}"><i data-lucide="trash-2"></i></button>`:''}</div></td></tr>`).join('')||'<tr><td colspan="8" class="grades-empty">No grade systems.</td></tr>';document.querySelectorAll('.system-edit').forEach(b=>b.onclick=()=>openSystem(Number(b.dataset.id)));document.querySelectorAll('.system-delete').forEach(b=>b.onclick=()=>deleteSystem(Number(b.dataset.id)));window.lucide?.createIcons();}
function renderRules(data){ruleRows=data;$('ruleBody').innerHTML=data.map((r,i)=>`<tr><td>${i+1}</td><td>${esc(r.system_name)}</td><td><strong>${esc(r.grade_name)}</strong></td><td>${number(r.min_percentage)}% - ${number(r.max_percentage)}%</td><td>${number(r.grade_point)}</td><td>${badge(r.result_status)}</td><td>${esc(r.remarks||'-')}</td><td>${badge(r.status)}</td><td><div class="grades-actions">${permissions.edit?`<button class="grades-action rule-edit" data-id="${r.id}"><i data-lucide="pencil"></i></button>`:''}${permissions.delete?`<button class="grades-action danger rule-delete" data-id="${r.id}"><i data-lucide="trash-2"></i></button>`:''}</div></td></tr>`).join('')||'<tr><td colspan="9" class="grades-empty">No grade rules.</td></tr>';document.querySelectorAll('.rule-edit').forEach(b=>b.onclick=()=>openRule(Number(b.dataset.id)));document.querySelectorAll('.rule-delete').forEach(b=>b.onclick=()=>deleteRule(Number(b.dataset.id)));window.lucide?.createIcons();}
function renderSummary(data){$('summaryBody').innerHTML=data.map(r=>`<tr><td><strong>${esc(r.grade_name)}</strong></td><td>${Number(r.students||0).toLocaleString('en-IN')}</td><td>${Number(r.passed||0).toLocaleString('en-IN')}</td><td>${Number(r.failed||0).toLocaleString('en-IN')}</td><td>${number(r.average_percentage)}%</td><td>${Number(r.published||0).toLocaleString('en-IN')}</td></tr>`).join('')||'<tr><td colspan="6" class="grades-empty">No grade report available.</td></tr>';}
function renderHistory(data){$('historyBody').innerHTML=data.map(r=>`<tr><td>${esc(r.created_at)}</td><td>${esc(r.action_name)}</td><td>${esc(r.record_label||'-')}</td><td>${esc(r.user_name||'-')}</td><td>${esc(r.details_text||'-')}</td></tr>`).join('')||'<tr><td colspan="5" class="grades-empty">No audit history.</td></tr>';}
function renderPagination(p={}){const total=Number(p.total||0),current=Number(p.page||1),per=Number(p.per_page||10),last=Math.max(1,Number(p.last_page||1)),start=total?((current-1)*per)+1:0,end=Math.min(current*per,total);$('recordInfo').textContent=`${total} grade record${total===1?'':'s'}`;$('pageInfo').textContent=`Showing ${start}-${end} of ${total}`;let html=`<button class="grades-page-button" data-page="${current-1}" ${current<=1?'disabled':''}>‹</button>`;for(let x=Math.max(1,current-2);x<=Math.min(last,current+2);x++)html+=`<button class="grades-page-button ${x===current?'active':''}" data-page="${x}">${x}</button>`;html+=`<button class="grades-page-button" data-page="${current+1}" ${current>=last?'disabled':''}>›</button>`;$('pagination').innerHTML=html;document.querySelectorAll('.grades-page-button').forEach(b=>b.onclick=()=>{if(!b.disabled){page=Number(b.dataset.page);load();}});}
async function load(){try{const r=await request('list',{search:$('search').value.trim(),academic_year_id:$('yearFilter').value,class_id:$('classFilter').value,section_id:$('sectionFilter').value,subject_id:$('subjectFilter').value,publish_status:$('publishFilter').value,page,per_page:10});meta=r.data.meta||meta;permissions=r.data.permissions||permissions;renderGrades(r.data.records||[]);renderSystems(r.data.systems||[]);renderRules(r.data.rules||[]);renderSummary(r.data.summary||[]);renderHistory(r.data.history||[]);renderPagination(r.data.pagination||{});updateStats(r.data.stats||{});if($('yearFilter').options.length<=1)fill('yearFilter',meta.years,'id','year_name','All Academic Years');if($('classFilter').options.length<=1)fill('classFilter',meta.classes,'id','class_label','All Classes');if($('sectionFilter').options.length<=1)fill('sectionFilter',meta.sections,'id','section_label','All Sections');if($('subjectFilter').options.length<=1)fill('subjectFilter',meta.subjects,'id','subject_name','All Subjects');}catch(e){message(e.message);}}
function openSystem(id=0){const r=systemRows.find(x=>Number(x.id)===id);$('systemId').value=r?.id||'';fill('systemYear',meta.years,'id','year_name','All Academic Years');$('systemName').value=r?.system_name||'';$('systemYear').value=r?.academic_year_id||'';$('calculationType').value=r?.calculation_type||'percentage';$('systemStatus').value=r?.status||'active';$('isDefault').value=Number(r?.is_default||0)?'1':'0';$('systemDescription').value=r?.description||'';$('systemModalTitle').textContent=r?'Edit Grade System':'Add Grade System';bootstrap.Modal.getOrCreateInstance($('systemModal')).show();}
function openRule(id=0){const r=ruleRows.find(x=>Number(x.id)===id);$('ruleId').value=r?.id||'';fill('ruleSystem',meta.systems,'id','system_name','Select grade system');$('ruleSystem').value=r?.grade_system_id||'';$('gradeName').value=r?.grade_name||'';$('minPercentage').value=r?.min_percentage??'';$('maxPercentage').value=r?.max_percentage??'';$('gradePoint').value=r?.grade_point??'';$('resultStatus').value=r?.result_status||'pass';$('ruleStatus').value=r?.status||'active';$('displayOrder').value=r?.display_order||0;$('ruleRemarks').value=r?.remarks||'';$('ruleModalTitle').textContent=r?'Edit Grade Rule':'Add Grade Rule';bootstrap.Modal.getOrCreateInstance($('ruleModal')).show();}
function filterStudents(){const year=Number($('gradeYear').value||0),classId=Number($('gradeClass').value||0),sectionId=Number($('gradeSection').value||0);const items=meta.students.filter(x=>(!year||!Number(x.academic_year_id)||Number(x.academic_year_id)===year)&&(!classId||!Number(x.class_id)||Number(x.class_id)===classId)&&(!sectionId||!Number(x.section_id)||Number(x.section_id)===sectionId));fill('gradeStudent',items,'id','student_label','Select student');}
function openGrade(id=0){const r=gradeRows.find(x=>Number(x.id)===id);$('studentGradeId').value=r?.id||'';fill('gradeYear',meta.years,'id','year_name','Select academic year');fill('gradeSystem',meta.systems,'id','system_name','Select grade system');fill('gradeClass',meta.classes,'id','class_label','Select class');fill('gradeSection',meta.sections,'id','section_label','No section');fill('gradeSubject',meta.subjects,'id','subject_name','Select subject');$('gradeYear').value=r?.academic_year_id||'';$('gradeSystem').value=r?.grade_system_id||meta.systems.find(x=>Number(x.is_default))?.id||'';$('gradeClass').value=r?.class_id||'';$('gradeSection').value=r?.section_id||'';filterStudents();$('gradeStudent').value=r?.student_id||'';$('gradeSubject').value=r?.subject_id||'';$('examName').value=r?.exam_name||'';$('examDate').value=r?.exam_date||'';$('marksObtained').value=r?.marks_obtained??'';$('maximumMarks').value=r?.maximum_marks||100;$('publishStatus').value=r?.publish_status||'draft';$('gradeRemarks').value=r?.remarks||'';$('gradeModalTitle').textContent=r?'Edit Student Grade':'Add Student Grade';bootstrap.Modal.getOrCreateInstance($('gradeModal')).show();}
async function viewGrade(id){try{const r=await request('detail',{id});const x=r.data.record;$('viewSubtitle').textContent=`${x.student_name} • ${x.exam_name}`;$('viewContent').innerHTML=[['Admission No.',x.admission_no],['Academic Year',x.academic_year_name],['Class / Section',`${x.class_name} / ${x.section_name||'-'}`],['Subject',x.subject_name],['Marks',`${number(x.marks_obtained)} / ${number(x.maximum_marks)}`],['Percentage',`${number(x.percentage)}%`],['Grade',x.grade_name],['Grade Point',number(x.grade_point)],['Result',x.result_status],['Publish',x.publish_status],['Exam Date',x.exam_date||'-'],['Created By',x.created_by_name||'-']].map(([l,v])=>`<div><small>${esc(l)}</small><strong>${esc(v)}</strong></div>`).join('');$('viewRemarks').textContent=x.remarks||'No remarks.';bootstrap.Modal.getOrCreateInstance($('viewModal')).show();}catch(e){message(e.message);}}
async function publishGrade(id){if(!confirm('Publish this grade result?'))return;try{const r=await request('publish',{id},'POST');message(r.message,true);await load();}catch(e){message(e.message);}}
async function deleteGrade(id){if(!confirm('Delete this student grade?'))return;try{const r=await request('delete_grade',{id},'POST');message(r.message,true);await load();}catch(e){message(e.message);}}
async function deleteSystem(id){if(!confirm('Delete this grade system?'))return;try{const r=await request('delete_system',{id},'POST');message(r.message,true);await load();}catch(e){message(e.message);}}
async function deleteRule(id){if(!confirm('Delete this grade rule?'))return;try{const r=await request('delete_rule',{id},'POST');message(r.message,true);await load();}catch(e){message(e.message);}}
$('systemForm').onsubmit=async e=>{e.preventDefault();try{const r=await request('save_system',{id:Number($('systemId').value||0),system_name:$('systemName').value.trim(),academic_year_id:Number($('systemYear').value||0),calculation_type:$('calculationType').value,status:$('systemStatus').value,is_default:Number($('isDefault').value||0),description:$('systemDescription').value.trim()},'POST');bootstrap.Modal.getInstance($('systemModal'))?.hide();message(r.message,true);await load();}catch(err){message(err.message);}};
$('ruleForm').onsubmit=async e=>{e.preventDefault();try{const r=await request('save_rule',{id:Number($('ruleId').value||0),grade_system_id:Number($('ruleSystem').value||0),grade_name:$('gradeName').value.trim(),min_percentage:Number($('minPercentage').value),max_percentage:Number($('maxPercentage').value),grade_point:Number($('gradePoint').value),result_status:$('resultStatus').value,status:$('ruleStatus').value,display_order:Number($('displayOrder').value||0),remarks:$('ruleRemarks').value.trim()},'POST');bootstrap.Modal.getInstance($('ruleModal'))?.hide();message(r.message,true);await load();}catch(err){message(err.message);}};
$('gradeForm').onsubmit=async e=>{e.preventDefault();try{const r=await request('save_grade',{id:Number($('studentGradeId').value||0),academic_year_id:Number($('gradeYear').value),grade_system_id:Number($('gradeSystem').value),class_id:Number($('gradeClass').value),section_id:Number($('gradeSection').value||0),student_id:Number($('gradeStudent').value),subject_id:Number($('gradeSubject').value),exam_name:$('examName').value.trim(),exam_date:$('examDate').value,marks_obtained:Number($('marksObtained').value),maximum_marks:Number($('maximumMarks').value),publish_status:$('publishStatus').value,remarks:$('gradeRemarks').value.trim()},'POST');bootstrap.Modal.getInstance($('gradeModal'))?.hide();message(r.message,true);await load();}catch(err){message(err.message);}};
$('addSystemBtn').onclick=$('panelAddSystemBtn').onclick=()=>openSystem();$('addRuleBtn').onclick=()=>openRule();$('addGradeBtn').onclick=$('panelAddGradeBtn').onclick=()=>openGrade();$('refreshBtn').onclick=load;$('gradeYear').onchange=filterStudents;$('gradeClass').onchange=filterStudents;$('gradeSection').onchange=filterStudents;
$('exportBtn').onclick=()=>{const p=new URLSearchParams({action:'export',search:$('search').value.trim(),academic_year_id:$('yearFilter').value,class_id:$('classFilter').value,section_id:$('sectionFilter').value,subject_id:$('subjectFilter').value,publish_status:$('publishFilter').value});window.location.href=apiUrl+'?'+p;};
$('printBtn').onclick=()=>{const p=new URLSearchParams({action:'print',search:$('search').value.trim(),academic_year_id:$('yearFilter').value,class_id:$('classFilter').value,section_id:$('sectionFilter').value,subject_id:$('subjectFilter').value,publish_status:$('publishFilter').value});window.open(apiUrl+'?'+p,'_blank');};
$('resetBtn').onclick=()=>{$('search').value='';['yearFilter','classFilter','sectionFilter','subjectFilter','publishFilter'].forEach(id=>$(id).value='all');page=1;load();};['yearFilter','classFilter','sectionFilter','subjectFilter','publishFilter'].forEach(id=>$(id).onchange=()=>{page=1;load();});let timer;$('search').oninput=()=>{clearTimeout(timer);timer=setTimeout(()=>{page=1;load();},300);};document.querySelectorAll('.grades-tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.grades-tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.grades-panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelector(`[data-panel="${b.dataset.tab}"]`)?.classList.add('active');});load();window.lucide?.createIcons();
})();
</script>
<?php require dirname(__DIR__) . '/includes/layout-end.php'; ?>
