<?php
declare(strict_types=1);

ob_start();
ini_set('display_errors','0');
error_reporting(E_ALL);
require_once dirname(__DIR__) . '/includes/bootstrap.php';

function grOut(bool $ok,string $message='',array $data=[],int $status=200):never{
    while(ob_get_level()>0)ob_end_clean();
    http_response_code($status);
    header('Content-Type: application/json; charset=utf-8');
    header('Cache-Control: no-store');
    echo json_encode(['success'=>$ok,'message'=>$message,'data'=>$data],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);
    exit;
}
function grInput():array{$d=json_decode((string)file_get_contents('php://input'),true);return is_array($d)?$d:$_POST;}
function grScope():array{$u=function_exists('current_user')?current_user():[];return['tenant_id'=>(int)($u['tenant_id']??$u['school_id']??$_SESSION['tenant_id']??0),'branch_id'=>(int)($u['branch_id']??$_SESSION['branch_id']??0),'user_id'=>(int)($u['id']??$u['user_id']??$_SESSION['user_id']??0),'role'=>(string)($u['role_name']??$u['role']??$_SESSION['role_name']??$_SESSION['role']??'')];}
function grCsrf(array $i):void{$s=(string)($_SESSION['grades_csrf_token']??'');$r=(string)($i['csrf_token']??'');if($s===''||$r===''||!hash_equals($s,$r))grOut(false,'Invalid or expired CSRF token. Refresh the page.',[],419);}
function grCan(array $s,string $action):bool{
    $role=strtolower(trim((string)$s['role']));
    if(in_array($role,['super_admin','super administrator','super admin','administrator','admin','school_admin','school admin','schooladmin','principal','teacher'],true))return true;
    if(function_exists('has_permission')){
        foreach(['grades_management','grade_management','examination_management','academic_management'] as $key){
            try{if(has_permission($key,$action))return true;}catch(Throwable $e){error_log('grades permission: '.$e->getMessage());}
        }
    }
    return $action==='view';
}
function grExists(PDO $pdo,string $table):bool{$q=$pdo->prepare("SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name=:t");$q->execute(['t'=>$table]);return(int)$q->fetchColumn()>0;}
function grName(string $a='s'):string{return "TRIM(CONCAT(COALESCE($a.first_name,''),CASE WHEN COALESCE($a.last_name,'')='' THEN '' ELSE CONCAT(' ',$a.last_name) END))";}
function grEnsure(PDO $pdo):void{
    $pdo->exec("CREATE TABLE IF NOT EXISTS grade_systems(
      id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,tenant_id BIGINT UNSIGNED NOT NULL,academic_year_id BIGINT UNSIGNED NULL,
      system_name VARCHAR(120) NOT NULL,calculation_type ENUM('percentage','marks','gpa') NOT NULL DEFAULT 'percentage',
      is_default TINYINT(1) NOT NULL DEFAULT 0,status ENUM('active','inactive') NOT NULL DEFAULT 'active',description VARCHAR(500) NULL,
      created_by BIGINT UNSIGNED NULL,updated_by BIGINT UNSIGNED NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY(id),
      UNIQUE KEY uq_grade_system(tenant_id,system_name,academic_year_id),KEY idx_grade_system(tenant_id,status)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
    $pdo->exec("CREATE TABLE IF NOT EXISTS grade_rules(
      id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,tenant_id BIGINT UNSIGNED NOT NULL,grade_system_id BIGINT UNSIGNED NOT NULL,
      grade_name VARCHAR(20) NOT NULL,min_percentage DECIMAL(6,2) NOT NULL,max_percentage DECIMAL(6,2) NOT NULL,
      grade_point DECIMAL(5,2) NOT NULL DEFAULT 0,result_status ENUM('pass','fail') NOT NULL DEFAULT 'pass',remarks VARCHAR(255) NULL,
      display_order INT NOT NULL DEFAULT 0,status ENUM('active','inactive') NOT NULL DEFAULT 'active',created_by BIGINT UNSIGNED NULL,
      updated_by BIGINT UNSIGNED NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      PRIMARY KEY(id),UNIQUE KEY uq_grade_rule(tenant_id,grade_system_id,grade_name),KEY idx_grade_rule_range(tenant_id,grade_system_id,status,min_percentage,max_percentage)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
    $pdo->exec("CREATE TABLE IF NOT EXISTS student_grades(
      id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,tenant_id BIGINT UNSIGNED NOT NULL,branch_id BIGINT UNSIGNED NULL,
      academic_year_id BIGINT UNSIGNED NOT NULL,academic_year_name VARCHAR(50) NOT NULL,class_id BIGINT UNSIGNED NOT NULL,
      class_name VARCHAR(150) NOT NULL,section_id BIGINT UNSIGNED NULL,section_name VARCHAR(100) NULL,student_id BIGINT UNSIGNED NOT NULL,
      student_name VARCHAR(220) NOT NULL,admission_no VARCHAR(50) NOT NULL,subject_id BIGINT UNSIGNED NOT NULL,subject_name VARCHAR(150) NOT NULL,
      exam_name VARCHAR(120) NOT NULL,exam_date DATE NULL,grade_system_id BIGINT UNSIGNED NOT NULL,grade_rule_id BIGINT UNSIGNED NOT NULL,
      marks_obtained DECIMAL(10,2) NOT NULL,maximum_marks DECIMAL(10,2) NOT NULL,percentage DECIMAL(7,2) NOT NULL,
      grade_name VARCHAR(20) NOT NULL,grade_point DECIMAL(5,2) NOT NULL,result_status ENUM('pass','fail') NOT NULL,
      publish_status ENUM('draft','published') NOT NULL DEFAULT 'draft',published_by BIGINT UNSIGNED NULL,published_at DATETIME NULL,
      remarks VARCHAR(255) NULL,created_by BIGINT UNSIGNED NULL,updated_by BIGINT UNSIGNED NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY(id),
      UNIQUE KEY uq_student_grade(tenant_id,academic_year_id,student_id,subject_id,exam_name),
      KEY idx_student_grade_filter(tenant_id,branch_id,academic_year_id,class_id,section_id,publish_status),KEY idx_student_grade_student(tenant_id,student_id)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
    $pdo->exec("CREATE TABLE IF NOT EXISTS grade_audit_logs(
      id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,tenant_id BIGINT UNSIGNED NOT NULL,branch_id BIGINT UNSIGNED NULL,
      record_type VARCHAR(40) NOT NULL,record_id BIGINT UNSIGNED NULL,action_name VARCHAR(80) NOT NULL,user_id BIGINT UNSIGNED NULL,
      record_label VARCHAR(180) NULL,details_json JSON NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(id),
      KEY idx_grade_audit(tenant_id,created_at)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
}
function grSeed(PDO $pdo,array $s):void{
    $q=$pdo->prepare("SELECT id FROM grade_systems WHERE tenant_id=:t ORDER BY is_default DESC,id LIMIT 1");$q->execute(['t'=>$s['tenant_id']]);$system=(int)$q->fetchColumn();
    if($system<=0){
        $q=$pdo->prepare("INSERT INTO grade_systems(tenant_id,academic_year_id,system_name,calculation_type,is_default,status,description,created_by,updated_by) VALUES(:t,NULL,'Standard Percentage Grading','percentage',1,'active','Default percentage based grading system',:u,:u2)");$q->execute(['t'=>$s['tenant_id'],'u'=>$s['user_id']?:null,'u2'=>$s['user_id']?:null]);$system=(int)$pdo->lastInsertId();
    }
    $rules=[['A+',90,100,10,'pass','Outstanding'],['A',80,89.99,9,'pass','Excellent'],['B+',70,79.99,8,'pass','Very Good'],['B',60,69.99,7,'pass','Good'],['C',50,59.99,6,'pass','Satisfactory'],['D',35,49.99,5,'pass','Pass'],['F',0,34.99,0,'fail','Needs Improvement']];
    $q=$pdo->prepare("INSERT INTO grade_rules(tenant_id,grade_system_id,grade_name,min_percentage,max_percentage,grade_point,result_status,remarks,display_order,status,created_by,updated_by) VALUES(:t,:s,:g,:mn,:mx,:gp,:rs,:r,:o,'active',:u,:u2) ON DUPLICATE KEY UPDATE min_percentage=VALUES(min_percentage),max_percentage=VALUES(max_percentage),grade_point=VALUES(grade_point),result_status=VALUES(result_status),remarks=VALUES(remarks),status='active'");
    foreach($rules as $idx=>$r)$q->execute(['t'=>$s['tenant_id'],'s'=>$system,'g'=>$r[0],'mn'=>$r[1],'mx'=>$r[2],'gp'=>$r[3],'rs'=>$r[4],'r'=>$r[5],'o'=>$idx+1,'u'=>$s['user_id']?:null,'u2'=>$s['user_id']?:null]);
}
function grAudit(PDO $pdo,array $s,string $type,?int $id,string $action,string $label,array $details=[]):void{$q=$pdo->prepare("INSERT INTO grade_audit_logs(tenant_id,branch_id,record_type,record_id,action_name,user_id,record_label,details_json) VALUES(:t,:b,:rt,:id,:a,:u,:l,:d)");$q->execute(['t'=>$s['tenant_id'],'b'=>$s['branch_id']?:null,'rt'=>$type,'id'=>$id,'a'=>$action,'u'=>$s['user_id']?:null,'l'=>substr($label,0,180),'d'=>json_encode($details,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)]);}
function grMeta(PDO $pdo,array $s):array{
    $q=$pdo->prepare("SELECT id,year_name FROM academic_years WHERE tenant_id=:t ORDER BY is_current DESC,id DESC");$q->execute(['t'=>$s['tenant_id']]);$years=$q->fetchAll(PDO::FETCH_ASSOC);
    $classes=[];
    if(grExists($pdo,'class_management_classes')){$q=$pdo->prepare("SELECT id,academic_year_id,class_name,section_name,CONCAT(class_name,' - ',section_name) class_label FROM class_management_classes WHERE tenant_id=:t AND status='active' ORDER BY display_order,class_name,section_name");$q->execute(['t'=>$s['tenant_id']]);$classes=$q->fetchAll(PDO::FETCH_ASSOC);}
    if(!$classes&&grExists($pdo,'classes')){$q=$pdo->prepare("SELECT id,academic_year_id,class_name,class_name class_label FROM classes WHERE tenant_id=:t AND status='active' ORDER BY display_order,class_name");$q->execute(['t'=>$s['tenant_id']]);$classes=$q->fetchAll(PDO::FETCH_ASSOC);}
    $sections=[];
    if(grExists($pdo,'school_sections')){$q=$pdo->prepare("SELECT id,class_id,academic_year_id,section_name,CONCAT(class_name_snapshot,' - ',section_name) section_label FROM school_sections WHERE tenant_id=:t AND status='active' ORDER BY display_order,section_name");$q->execute(['t'=>$s['tenant_id']]);$sections=$q->fetchAll(PDO::FETCH_ASSOC);}
    if(!$sections&&grExists($pdo,'sections')){$q=$pdo->prepare("SELECT id,class_id,NULL academic_year_id,section_name,section_name section_label FROM sections WHERE tenant_id=:t AND status='active' ORDER BY section_name");$q->execute(['t'=>$s['tenant_id']]);$sections=$q->fetchAll(PDO::FETCH_ASSOC);}
    $subjects=[];
    if(grExists($pdo,'school_subjects')){$q=$pdo->prepare("SELECT id,academic_year_id,subject_name,subject_code,maximum_marks,pass_marks FROM school_subjects WHERE tenant_id=:t AND status='active' ORDER BY display_order,subject_name");$q->execute(['t'=>$s['tenant_id']]);$subjects=$q->fetchAll(PDO::FETCH_ASSOC);}
    if(!$subjects&&grExists($pdo,'subjects')){$q=$pdo->prepare("SELECT id,NULL academic_year_id,subject_name,subject_code,100 maximum_marks,35 pass_marks FROM subjects WHERE tenant_id=:t AND status='active' ORDER BY subject_name");$q->execute(['t'=>$s['tenant_id']]);$subjects=$q->fetchAll(PDO::FETCH_ASSOC);}
    $students=[];
    if(grExists($pdo,'student_enrollments')){$q=$pdo->prepare("SELECT st.id,CONCAT(".grName('st').",' (',st.admission_no,')') student_label,".grName('st')." student_name,st.admission_no,se.academic_year_id,se.class_id,se.section_id FROM students st LEFT JOIN student_enrollments se ON se.student_id=st.id AND se.tenant_id=st.tenant_id AND se.enrollment_status='active' WHERE st.tenant_id=:t AND (:bs=0 OR st.branch_id=:b) AND st.status='active' AND st.deleted_at IS NULL ORDER BY st.first_name,st.last_name");$q->execute(['t'=>$s['tenant_id'],'bs'=>$s['branch_id'],'b'=>$s['branch_id']]);$students=$q->fetchAll(PDO::FETCH_ASSOC);}else{$q=$pdo->prepare("SELECT st.id,CONCAT(".grName('st').",' (',st.admission_no,')') student_label,".grName('st')." student_name,st.admission_no,NULL academic_year_id,NULL class_id,NULL section_id FROM students st WHERE st.tenant_id=:t AND (:bs=0 OR st.branch_id=:b) AND st.status='active' AND st.deleted_at IS NULL ORDER BY st.first_name,st.last_name");$q->execute(['t'=>$s['tenant_id'],'bs'=>$s['branch_id'],'b'=>$s['branch_id']]);$students=$q->fetchAll(PDO::FETCH_ASSOC);}
    $q=$pdo->prepare("SELECT gs.*,ay.year_name,(SELECT COUNT(*) FROM grade_rules r WHERE r.grade_system_id=gs.id AND r.tenant_id=gs.tenant_id) rule_count FROM grade_systems gs LEFT JOIN academic_years ay ON ay.id=gs.academic_year_id WHERE gs.tenant_id=:t ORDER BY gs.is_default DESC,gs.system_name");$q->execute(['t'=>$s['tenant_id']]);$systems=$q->fetchAll(PDO::FETCH_ASSOC);
    return compact('years','classes','sections','subjects','students','systems');
}
function grWhere(array $s,array $f,array &$p):array{$where=['g.tenant_id=:t','(:bs=0 OR g.branch_id=:b)'];$p=['t'=>$s['tenant_id'],'bs'=>$s['branch_id'],'b'=>$s['branch_id']];$search=trim((string)($f['search']??''));if($search!==''){$where[]='(g.student_name LIKE :q OR g.admission_no LIKE :q OR g.exam_name LIKE :q OR g.subject_name LIKE :q)';$p['q']='%'.$search.'%';}foreach(['academic_year_id'=>'y','class_id'=>'c','section_id'=>'sec','subject_id'=>'sub'] as $field=>$param){if(!empty($f[$field])&&$f[$field]!=='all'){$where[]="g.$field=:$param";$p[$param]=(int)$f[$field];}}if(!empty($f['publish_status'])&&$f['publish_status']!=='all'){$where[]='g.publish_status=:ps';$p['ps']=$f['publish_status'];}return$where;}
function grRows(PDO $pdo,array $s,array $f,int $page,int $per):array{$p=[];$where=grWhere($s,$f,$p);$q=$pdo->prepare("SELECT COUNT(*) FROM student_grades g WHERE ".implode(' AND ',$where));$q->execute($p);$total=(int)$q->fetchColumn();$last=max(1,(int)ceil($total/$per));$page=min(max(1,$page),$last);$offset=($page-1)*$per;$userJoin='';$userSelect='NULL created_by_name';if(grExists($pdo,'users')){$userJoin=' LEFT JOIN users u ON u.id=g.created_by ';$userSelect="COALESCE(u.name,u.username,u.email,'-') created_by_name";}$q=$pdo->prepare("SELECT g.*,$userSelect FROM student_grades g $userJoin WHERE ".implode(' AND ',$where)." ORDER BY g.exam_date DESC,g.id DESC LIMIT {$per} OFFSET {$offset}");$q->execute($p);$rows=$q->fetchAll(PDO::FETCH_ASSOC);foreach($rows as $idx=>&$r)$r['row_number']=$offset+$idx+1;return['records'=>$rows,'pagination'=>['total'=>$total,'page'=>$page,'per_page'=>$per,'last_page'=>$last]];}
function grStats(PDO $pdo,array $s):array{$q=$pdo->prepare("SELECT (SELECT COUNT(*) FROM grade_systems WHERE tenant_id=:t1) total_systems,(SELECT COUNT(*) FROM grade_rules WHERE tenant_id=:t2 AND status='active') active_rules,(SELECT COUNT(DISTINCT student_id) FROM student_grades WHERE tenant_id=:t3 AND (:bs=0 OR branch_id=:b)) students_evaluated,(SELECT COUNT(*) FROM student_grades WHERE tenant_id=:t4 AND (:bs2=0 OR branch_id=:b2) AND publish_status='published') published_results");$q->execute(['t1'=>$s['tenant_id'],'t2'=>$s['tenant_id'],'t3'=>$s['tenant_id'],'bs'=>$s['branch_id'],'b'=>$s['branch_id'],'t4'=>$s['tenant_id'],'bs2'=>$s['branch_id'],'b2'=>$s['branch_id']]);return$q->fetch(PDO::FETCH_ASSOC)?:[];}
function grRules(PDO $pdo,array $s):array{$q=$pdo->prepare("SELECT r.*,gs.system_name FROM grade_rules r INNER JOIN grade_systems gs ON gs.id=r.grade_system_id WHERE r.tenant_id=:t ORDER BY gs.system_name,r.display_order,r.max_percentage DESC");$q->execute(['t'=>$s['tenant_id']]);return$q->fetchAll(PDO::FETCH_ASSOC);}
function grSummary(PDO $pdo,array $s):array{$q=$pdo->prepare("SELECT grade_name,COUNT(*) students,SUM(result_status='pass') passed,SUM(result_status='fail') failed,ROUND(AVG(percentage),2) average_percentage,SUM(publish_status='published') published FROM student_grades WHERE tenant_id=:t AND (:bs=0 OR branch_id=:b) GROUP BY grade_name ORDER BY MAX(percentage) DESC");$q->execute(['t'=>$s['tenant_id'],'bs'=>$s['branch_id'],'b'=>$s['branch_id']]);return$q->fetchAll(PDO::FETCH_ASSOC);}
function grHistory(PDO $pdo,array $s):array{$userJoin='';$userSelect='NULL user_name';if(grExists($pdo,'users')){$userJoin=' LEFT JOIN users u ON u.id=a.user_id ';$userSelect="COALESCE(u.name,u.username,u.email,'-') user_name";}$q=$pdo->prepare("SELECT a.created_at,a.action_name,a.record_label,$userSelect,LEFT(REPLACE(REPLACE(COALESCE(a.details_json,''),CHAR(10),' '),CHAR(13),' '),300) details_text FROM grade_audit_logs a $userJoin WHERE a.tenant_id=:t ORDER BY a.id DESC LIMIT 100");$q->execute(['t'=>$s['tenant_id']]);return$q->fetchAll(PDO::FETCH_ASSOC);}
function grLookup(PDO $pdo,array $s,string $type,int $id):array{
    if($type==='year'){$q=$pdo->prepare("SELECT id,year_name label FROM academic_years WHERE id=:id AND tenant_id=:t");}
    elseif($type==='class'&&grExists($pdo,'class_management_classes')){$q=$pdo->prepare("SELECT id,class_name label,section_name extra FROM class_management_classes WHERE id=:id AND tenant_id=:t");}
    elseif($type==='class'){$q=$pdo->prepare("SELECT id,class_name label,NULL extra FROM classes WHERE id=:id AND tenant_id=:t");}
    elseif($type==='section'&&grExists($pdo,'school_sections')){$q=$pdo->prepare("SELECT id,section_name label,NULL extra FROM school_sections WHERE id=:id AND tenant_id=:t");}
    elseif($type==='section'){$q=$pdo->prepare("SELECT id,section_name label,NULL extra FROM sections WHERE id=:id AND tenant_id=:t");}
    elseif($type==='subject'&&grExists($pdo,'school_subjects')){$q=$pdo->prepare("SELECT id,subject_name label,NULL extra FROM school_subjects WHERE id=:id AND tenant_id=:t");}
    elseif($type==='subject'){$q=$pdo->prepare("SELECT id,subject_name label,NULL extra FROM subjects WHERE id=:id AND tenant_id=:t");}
    elseif($type==='student'){$q=$pdo->prepare("SELECT id,".grName('students')." label,admission_no extra FROM students WHERE id=:id AND tenant_id=:t AND deleted_at IS NULL");}
    else throw new InvalidArgumentException('Invalid reference lookup.');
    $q->execute(['id'=>$id,'t'=>$s['tenant_id']]);$r=$q->fetch(PDO::FETCH_ASSOC);if(!$r)throw new InvalidArgumentException('Selected reference record is unavailable.');return$r;
}

if(!isset($pdo)||!$pdo instanceof PDO)grOut(false,'Database connection unavailable.',[],500);
if(session_status()!==PHP_SESSION_ACTIVE)session_start();
if(empty($_SESSION['grades_csrf_token']))$_SESSION['grades_csrf_token']=bin2hex(random_bytes(32));
$s=grScope();if($s['tenant_id']<=0||$s['user_id']<=0)grOut(false,'Tenant or user session is missing.',[],401);
grEnsure($pdo);grSeed($pdo,$s);$i=grInput();$action=strtolower(trim((string)($i['action']??$_GET['action']??'')));

try{
    if($action==='list'){$page=max(1,(int)($_GET['page']??1));$per=min(100,max(5,(int)($_GET['per_page']??10)));$x=grRows($pdo,$s,$_GET,$page,$per);$m=grMeta($pdo,$s);grOut(true,'Grades management loaded.',['records'=>$x['records'],'pagination'=>$x['pagination'],'stats'=>grStats($pdo,$s),'systems'=>$m['systems'],'rules'=>grRules($pdo,$s),'summary'=>grSummary($pdo,$s),'history'=>grHistory($pdo,$s),'meta'=>$m,'permissions'=>['edit'=>grCan($s,'edit')||grCan($s,'create'),'delete'=>grCan($s,'delete'),'publish'=>grCan($s,'publish')||grCan($s,'approve')||grCan($s,'edit')],'csrf_token'=>$_SESSION['grades_csrf_token']]);}
    if($action==='detail'){$id=(int)($_GET['id']??0);$userJoin='';$userSelect='NULL created_by_name';if(grExists($pdo,'users')){$userJoin=' LEFT JOIN users u ON u.id=g.created_by ';$userSelect="COALESCE(u.name,u.username,u.email,'-') created_by_name";}$q=$pdo->prepare("SELECT g.*,$userSelect FROM student_grades g $userJoin WHERE g.id=:id AND g.tenant_id=:t AND (:bs=0 OR g.branch_id=:b)");$q->execute(['id'=>$id,'t'=>$s['tenant_id'],'bs'=>$s['branch_id'],'b'=>$s['branch_id']]);$r=$q->fetch(PDO::FETCH_ASSOC);if(!$r)throw new InvalidArgumentException('Student grade record not found.');grOut(true,'Student grade loaded.',['record'=>$r]);}
    if($action==='save_system'){
        grCsrf($i);if(!grCan($s,'edit')&&!grCan($s,'create'))grOut(false,'You do not have permission to save grade systems.',[],403);
        $id=(int)($i['id']??0);$name=trim((string)($i['system_name']??''));$year=(int)($i['academic_year_id']??0);$calc=(string)($i['calculation_type']??'percentage');$status=(string)($i['status']??'active');$default=!empty($i['is_default'])?1:0;$description=trim((string)($i['description']??''));
        if($name==='')throw new InvalidArgumentException('Grade system name is required.');if(!in_array($calc,['percentage','marks','gpa'],true)||!in_array($status,['active','inactive'],true))throw new InvalidArgumentException('Invalid grade system values.');
        $pdo->beginTransaction();if($default)$pdo->prepare("UPDATE grade_systems SET is_default=0 WHERE tenant_id=:t")->execute(['t'=>$s['tenant_id']]);
        if($id>0){$q=$pdo->prepare("UPDATE grade_systems SET academic_year_id=:y,system_name=:n,calculation_type=:c,is_default=:d,status=:s,description=:ds,updated_by=:u WHERE id=:id AND tenant_id=:t");$q->execute(['y'=>$year?:null,'n'=>$name,'c'=>$calc,'d'=>$default,'s'=>$status,'ds'=>$description?:null,'u'=>$s['user_id'],'id'=>$id,'t'=>$s['tenant_id']]);if(!$q->rowCount()){$q=$pdo->prepare("SELECT id FROM grade_systems WHERE id=:id AND tenant_id=:t");$q->execute(['id'=>$id,'t'=>$s['tenant_id']]);if(!$q->fetchColumn())throw new InvalidArgumentException('Grade system not found.');}$message='Grade system updated successfully.';}else{$q=$pdo->prepare("INSERT INTO grade_systems(tenant_id,academic_year_id,system_name,calculation_type,is_default,status,description,created_by,updated_by) VALUES(:t,:y,:n,:c,:d,:s,:ds,:u,:u2)");$q->execute(['t'=>$s['tenant_id'],'y'=>$year?:null,'n'=>$name,'c'=>$calc,'d'=>$default,'s'=>$status,'ds'=>$description?:null,'u'=>$s['user_id'],'u2'=>$s['user_id']]);$id=(int)$pdo->lastInsertId();$message='Grade system created successfully.';}grAudit($pdo,$s,'system',$id,$id?'save_system':'create_system',$name,$i);$pdo->commit();grOut(true,$message,['id'=>$id]);
    }
    if($action==='delete_system'){
        grCsrf($i);if(!grCan($s,'delete'))grOut(false,'You do not have permission to delete grade systems.',[],403);$id=(int)($i['id']??0);$q=$pdo->prepare("SELECT system_name,is_default FROM grade_systems WHERE id=:id AND tenant_id=:t");$q->execute(['id'=>$id,'t'=>$s['tenant_id']]);$r=$q->fetch(PDO::FETCH_ASSOC);if(!$r)throw new InvalidArgumentException('Grade system not found.');if((int)$r['is_default']===1)throw new InvalidArgumentException('The default grade system cannot be deleted.');$q=$pdo->prepare("SELECT (SELECT COUNT(*) FROM grade_rules WHERE grade_system_id=:id1)+(SELECT COUNT(*) FROM student_grades WHERE grade_system_id=:id2)");$q->execute(['id1'=>$id,'id2'=>$id]);if((int)$q->fetchColumn()>0)throw new InvalidArgumentException('Grade system is already used by rules or student grades.');$pdo->prepare("DELETE FROM grade_systems WHERE id=:id AND tenant_id=:t")->execute(['id'=>$id,'t'=>$s['tenant_id']]);grAudit($pdo,$s,'system',$id,'delete_system',$r['system_name'],$r);grOut(true,'Grade system deleted successfully.');
    }
    if($action==='save_rule'){
        grCsrf($i);if(!grCan($s,'edit')&&!grCan($s,'create'))grOut(false,'You do not have permission to save grade rules.',[],403);$id=(int)($i['id']??0);$system=(int)($i['grade_system_id']??0);$grade=strtoupper(trim((string)($i['grade_name']??'')));$min=round((float)($i['min_percentage']??0),2);$max=round((float)($i['max_percentage']??0),2);$point=round((float)($i['grade_point']??0),2);$result=(string)($i['result_status']??'pass');$status=(string)($i['status']??'active');$order=max(0,min(9999,(int)($i['display_order']??0)));$remarks=trim((string)($i['remarks']??''));
        if($system<=0||$grade==='')throw new InvalidArgumentException('Grade system and grade name are required.');if($min<0||$max>100||$min>$max)throw new InvalidArgumentException('Enter a valid percentage range between 0 and 100.');if($point<0||$point>10)throw new InvalidArgumentException('Grade point must be between 0 and 10.');if(!in_array($result,['pass','fail'],true)||!in_array($status,['active','inactive'],true))throw new InvalidArgumentException('Invalid grade rule values.');
        $q=$pdo->prepare("SELECT COUNT(*) FROM grade_systems WHERE id=:id AND tenant_id=:t");$q->execute(['id'=>$system,'t'=>$s['tenant_id']]);if(!(int)$q->fetchColumn())throw new InvalidArgumentException('Invalid grade system.');$q=$pdo->prepare("SELECT COUNT(*) FROM grade_rules WHERE tenant_id=:t AND grade_system_id=:s AND id<>:id AND status='active' AND NOT(max_percentage<:mn OR min_percentage>:mx)");$q->execute(['t'=>$s['tenant_id'],'s'=>$system,'id'=>$id,'mn'=>$min,'mx'=>$max]);if((int)$q->fetchColumn()>0)throw new InvalidArgumentException('This percentage range overlaps another active rule.');
        if($id>0){$q=$pdo->prepare("UPDATE grade_rules SET grade_system_id=:s,grade_name=:g,min_percentage=:mn,max_percentage=:mx,grade_point=:gp,result_status=:rs,remarks=:r,display_order=:o,status=:st,updated_by=:u WHERE id=:id AND tenant_id=:t");$q->execute(['s'=>$system,'g'=>$grade,'mn'=>$min,'mx'=>$max,'gp'=>$point,'rs'=>$result,'r'=>$remarks?:null,'o'=>$order,'st'=>$status,'u'=>$s['user_id'],'id'=>$id,'t'=>$s['tenant_id']]);$message='Grade rule updated successfully.';}else{$q=$pdo->prepare("INSERT INTO grade_rules(tenant_id,grade_system_id,grade_name,min_percentage,max_percentage,grade_point,result_status,remarks,display_order,status,created_by,updated_by) VALUES(:t,:s,:g,:mn,:mx,:gp,:rs,:r,:o,:st,:u,:u2)");$q->execute(['t'=>$s['tenant_id'],'s'=>$system,'g'=>$grade,'mn'=>$min,'mx'=>$max,'gp'=>$point,'rs'=>$result,'r'=>$remarks?:null,'o'=>$order,'st'=>$status,'u'=>$s['user_id'],'u2'=>$s['user_id']]);$id=(int)$pdo->lastInsertId();$message='Grade rule created successfully.';}grAudit($pdo,$s,'rule',$id,'save_rule',$grade,$i);grOut(true,$message,['id'=>$id]);
    }
    if($action==='delete_rule'){
        grCsrf($i);if(!grCan($s,'delete'))grOut(false,'You do not have permission to delete grade rules.',[],403);$id=(int)($i['id']??0);$q=$pdo->prepare("SELECT grade_name FROM grade_rules WHERE id=:id AND tenant_id=:t");$q->execute(['id'=>$id,'t'=>$s['tenant_id']]);$name=$q->fetchColumn();if($name===false)throw new InvalidArgumentException('Grade rule not found.');$q=$pdo->prepare("SELECT COUNT(*) FROM student_grades WHERE grade_rule_id=:id");$q->execute(['id'=>$id]);if((int)$q->fetchColumn()>0)throw new InvalidArgumentException('Grade rule is already used by student grade records.');$pdo->prepare("DELETE FROM grade_rules WHERE id=:id AND tenant_id=:t")->execute(['id'=>$id,'t'=>$s['tenant_id']]);grAudit($pdo,$s,'rule',$id,'delete_rule',(string)$name);grOut(true,'Grade rule deleted successfully.');
    }
    if($action==='save_grade'){
        grCsrf($i);if(!grCan($s,'edit')&&!grCan($s,'create'))grOut(false,'You do not have permission to save student grades.',[],403);$id=(int)($i['id']??0);$year=(int)($i['academic_year_id']??0);$system=(int)($i['grade_system_id']??0);$class=(int)($i['class_id']??0);$section=(int)($i['section_id']??0);$student=(int)($i['student_id']??0);$subject=(int)($i['subject_id']??0);$exam=trim((string)($i['exam_name']??''));$examDate=trim((string)($i['exam_date']??''));$marks=round((float)($i['marks_obtained']??0),2);$maximum=round((float)($i['maximum_marks']??0),2);$publish=(string)($i['publish_status']??'draft');$remarks=trim((string)($i['remarks']??''));
        if($year<=0||$system<=0||$class<=0||$student<=0||$subject<=0||$exam==='')throw new InvalidArgumentException('Academic year, grade system, class, student, subject and exam name are required.');if($maximum<=0||$marks<0||$marks>$maximum)throw new InvalidArgumentException('Marks obtained must be between 0 and maximum marks.');if(!in_array($publish,['draft','published'],true))throw new InvalidArgumentException('Invalid publish status.');if($examDate!==''&&!preg_match('/^\d{4}-\d{2}-\d{2}$/',$examDate))throw new InvalidArgumentException('Invalid exam date.');
        $percentage=round(($marks/$maximum)*100,2);$q=$pdo->prepare("SELECT * FROM grade_rules WHERE tenant_id=:t AND grade_system_id=:s AND status='active' AND :p BETWEEN min_percentage AND max_percentage ORDER BY min_percentage DESC LIMIT 1");$q->execute(['t'=>$s['tenant_id'],'s'=>$system,'p'=>$percentage]);$rule=$q->fetch(PDO::FETCH_ASSOC);if(!$rule)throw new InvalidArgumentException('No active grade rule matches the calculated percentage.');
        $yearR=grLookup($pdo,$s,'year',$year);$classR=grLookup($pdo,$s,'class',$class);$sectionName='';if($section>0)$sectionName=(string)grLookup($pdo,$s,'section',$section)['label'];elseif(!empty($classR['extra']))$sectionName=(string)$classR['extra'];$subjectR=grLookup($pdo,$s,'subject',$subject);$studentR=grLookup($pdo,$s,'student',$student);
        $pdo->beginTransaction();if($id>0){$q=$pdo->prepare("UPDATE student_grades SET academic_year_id=:y,academic_year_name=:yn,class_id=:c,class_name=:cn,section_id=:sec,section_name=:sn,student_id=:st,student_name=:stn,admission_no=:ad,subject_id=:sub,subject_name=:subn,exam_name=:e,exam_date=:ed,grade_system_id=:gs,grade_rule_id=:gr,marks_obtained=:m,maximum_marks=:mx,percentage=:p,grade_name=:gn,grade_point=:gp,result_status=:rs,publish_status=:ps,published_by=CASE WHEN :ps2='published' THEN :u ELSE NULL END,published_at=CASE WHEN :ps3='published' THEN NOW() ELSE NULL END,remarks=:r,updated_by=:u2 WHERE id=:id AND tenant_id=:t");$q->execute(['y'=>$year,'yn'=>$yearR['label'],'c'=>$class,'cn'=>$classR['label'],'sec'=>$section?:null,'sn'=>$sectionName?:null,'st'=>$student,'stn'=>$studentR['label'],'ad'=>$studentR['extra'],'sub'=>$subject,'subn'=>$subjectR['label'],'e'=>$exam,'ed'=>$examDate?:null,'gs'=>$system,'gr'=>$rule['id'],'m'=>$marks,'mx'=>$maximum,'p'=>$percentage,'gn'=>$rule['grade_name'],'gp'=>$rule['grade_point'],'rs'=>$rule['result_status'],'ps'=>$publish,'ps2'=>$publish,'u'=>$s['user_id'],'ps3'=>$publish,'r'=>$remarks?:null,'u2'=>$s['user_id'],'id'=>$id,'t'=>$s['tenant_id']]);$message='Student grade updated successfully.';}else{$q=$pdo->prepare("INSERT INTO student_grades(tenant_id,branch_id,academic_year_id,academic_year_name,class_id,class_name,section_id,section_name,student_id,student_name,admission_no,subject_id,subject_name,exam_name,exam_date,grade_system_id,grade_rule_id,marks_obtained,maximum_marks,percentage,grade_name,grade_point,result_status,publish_status,published_by,published_at,remarks,created_by,updated_by) VALUES(:t,:b,:y,:yn,:c,:cn,:sec,:sn,:st,:stn,:ad,:sub,:subn,:e,:ed,:gs,:gr,:m,:mx,:p,:gn,:gp,:rs,:ps,:pb,:pa,:r,:u,:u2)");$q->execute(['t'=>$s['tenant_id'],'b'=>$s['branch_id']?:null,'y'=>$year,'yn'=>$yearR['label'],'c'=>$class,'cn'=>$classR['label'],'sec'=>$section?:null,'sn'=>$sectionName?:null,'st'=>$student,'stn'=>$studentR['label'],'ad'=>$studentR['extra'],'sub'=>$subject,'subn'=>$subjectR['label'],'e'=>$exam,'ed'=>$examDate?:null,'gs'=>$system,'gr'=>$rule['id'],'m'=>$marks,'mx'=>$maximum,'p'=>$percentage,'gn'=>$rule['grade_name'],'gp'=>$rule['grade_point'],'rs'=>$rule['result_status'],'ps'=>$publish,'pb'=>$publish==='published'?$s['user_id']:null,'pa'=>$publish==='published'?date('Y-m-d H:i:s'):null,'r'=>$remarks?:null,'u'=>$s['user_id'],'u2'=>$s['user_id']]);$id=(int)$pdo->lastInsertId();$message='Student grade created successfully.';}grAudit($pdo,$s,'student_grade',$id,'save_grade',$studentR['label'].' - '.$exam,['percentage'=>$percentage,'grade'=>$rule['grade_name'],'result'=>$rule['result_status']]);$pdo->commit();grOut(true,$message,['id'=>$id,'percentage'=>$percentage,'grade_name'=>$rule['grade_name'],'grade_point'=>$rule['grade_point'],'result_status'=>$rule['result_status']]);
    }
    if($action==='publish'){
        grCsrf($i);if(!grCan($s,'publish')&&!grCan($s,'approve')&&!grCan($s,'edit'))grOut(false,'You do not have permission to publish grades.',[],403);$id=(int)($i['id']??0);$q=$pdo->prepare("SELECT student_name,exam_name FROM student_grades WHERE id=:id AND tenant_id=:t AND (:bs=0 OR branch_id=:b)");$q->execute(['id'=>$id,'t'=>$s['tenant_id'],'bs'=>$s['branch_id'],'b'=>$s['branch_id']]);$r=$q->fetch(PDO::FETCH_ASSOC);if(!$r)throw new InvalidArgumentException('Student grade record not found.');$pdo->prepare("UPDATE student_grades SET publish_status='published',published_by=:u,published_at=NOW(),updated_by=:u2 WHERE id=:id AND tenant_id=:t")->execute(['u'=>$s['user_id'],'u2'=>$s['user_id'],'id'=>$id,'t'=>$s['tenant_id']]);grAudit($pdo,$s,'student_grade',$id,'publish_grade',$r['student_name'].' - '.$r['exam_name']);grOut(true,'Student grade published successfully.');
    }
    if($action==='delete_grade'){
        grCsrf($i);if(!grCan($s,'delete'))grOut(false,'You do not have permission to delete student grades.',[],403);$id=(int)($i['id']??0);$q=$pdo->prepare("SELECT student_name,exam_name,publish_status FROM student_grades WHERE id=:id AND tenant_id=:t AND (:bs=0 OR branch_id=:b)");$q->execute(['id'=>$id,'t'=>$s['tenant_id'],'bs'=>$s['branch_id'],'b'=>$s['branch_id']]);$r=$q->fetch(PDO::FETCH_ASSOC);if(!$r)throw new InvalidArgumentException('Student grade record not found.');if($r['publish_status']==='published'&&!grCan($s,'approve'))throw new InvalidArgumentException('Published results require approval permission before deletion.');$pdo->prepare("DELETE FROM student_grades WHERE id=:id AND tenant_id=:t")->execute(['id'=>$id,'t'=>$s['tenant_id']]);grAudit($pdo,$s,'student_grade',$id,'delete_grade',$r['student_name'].' - '.$r['exam_name'],$r);grOut(true,'Student grade deleted successfully.');
    }
    if($action==='export'||$action==='print'){
        $x=grRows($pdo,$s,$_GET,1,5000);if($action==='export'){while(ob_get_level()>0)ob_end_clean();header('Content-Type:text/csv; charset=utf-8');header('Content-Disposition:attachment; filename="grades-report-'.date('Ymd-His').'.csv"');$f=fopen('php://output','wb');fputcsv($f,['Student','Admission No','Academic Year','Class','Section','Exam','Subject','Marks','Maximum Marks','Percentage','Grade','Grade Point','Result','Publish Status']);foreach($x['records'] as $r)fputcsv($f,[$r['student_name'],$r['admission_no'],$r['academic_year_name'],$r['class_name'],$r['section_name'],$r['exam_name'],$r['subject_name'],$r['marks_obtained'],$r['maximum_marks'],$r['percentage'],$r['grade_name'],$r['grade_point'],$r['result_status'],$r['publish_status']]);fclose($f);exit;}
        while(ob_get_level()>0)ob_end_clean();header('Content-Type:text/html; charset=utf-8');$e=fn($v)=>htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');echo '<!doctype html><html><head><meta charset="utf-8"><title>Grades Report</title><style>body{font-family:Arial;margin:24px}h2{text-align:center;color:#101b46}table{width:100%;border-collapse:collapse;font-size:10px}th,td{border:1px solid #ddd;padding:7px;text-align:left}th{background:#f4f6fa}.actions{text-align:center;margin:18px}@media print{.actions{display:none}}</style></head><body><h2>Student Grades Report</h2><table><thead><tr><th>Student</th><th>Admission</th><th>Year</th><th>Class</th><th>Exam</th><th>Subject</th><th>Marks</th><th>%</th><th>Grade</th><th>Result</th><th>Publish</th></tr></thead><tbody>';foreach($x['records'] as $r)echo '<tr><td>'.$e($r['student_name']).'</td><td>'.$e($r['admission_no']).'</td><td>'.$e($r['academic_year_name']).'</td><td>'.$e($r['class_name'].' / '.($r['section_name']?:'-')).'</td><td>'.$e($r['exam_name']).'</td><td>'.$e($r['subject_name']).'</td><td>'.$e($r['marks_obtained'].' / '.$r['maximum_marks']).'</td><td>'.$e($r['percentage']).'</td><td>'.$e($r['grade_name']).'</td><td>'.$e($r['result_status']).'</td><td>'.$e($r['publish_status']).'</td></tr>';echo '</tbody></table><div class="actions"><button onclick="window.print()">Print Report</button></div></body></html>';exit;
    }
    grOut(false,'Invalid Grades Management action.',[],400);
}catch(PDOException $e){if($pdo->inTransaction())$pdo->rollBack();error_log('grades database: '.$e->getMessage());if((string)$e->getCode()==='23000')grOut(false,'A duplicate grade system, rule, or student grade already exists.',[],409);$h=strtolower((string)($_SERVER['HTTP_HOST']??''));grOut(false,(str_contains($h,'localhost')||str_contains($h,'127.0.0.1'))?'Grades database request failed: '.$e->getMessage():'Unable to complete the grades request.',[],500);
}catch(InvalidArgumentException $e){if($pdo->inTransaction())$pdo->rollBack();grOut(false,$e->getMessage(),[],422);
}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();error_log('grades.php: '.$e->getMessage());$h=strtolower((string)($_SERVER['HTTP_HOST']??''));grOut(false,(str_contains($h,'localhost')||str_contains($h,'127.0.0.1'))?'Grades request failed: '.$e->getMessage():'Unable to complete the grades request.',[],500);}
